### ISSUE TITLE
Training data; not a issue!

### ISSUE THREAD

**Issue by gaziway** [chao-su/prnnlm#1]
Hi, 

We would like to train a model with new data. Could you please be kind and share at least few lines of your training data, so we could prepare ours according to it.

thank you!

**Comment by chao-su** [comment]
Hi, @gaziway ,sorry for the late reply!
I have added some example data for training and testing. You may check the 'example-data' directory. And I also added an example command for running it ('cmd-swb.sh') .
Please feel free to contact with me if you have any question.

**Comment by gaziway** [comment]
Thank you very much, it works like a charm!
Yet I have another question on top of my mind: what would you recommend to do in order to train a char level model when using your solution. One possible approach would be to treat each char as a separate word and associate each char ch{i,j} of a word w{i} with a w{i}s original POS tag.

word level representation example:
|0| i |1| guess
char level representation:
|0| i |1| g |1| u |1| e |1| s |1| s |1| 

I would like to hear your suggestions. 
Thank you!

**Comment by chao-su** [comment]
It may depend on what your tags of characters mean. If all characters of a word have the same tag (|1| g |1| u |1| e |1| s |1| s |1|), then you can use the word level representation for simplicity (|1| guess). But if each char has different tag (|1| g |2| u |5| e ...), you should use the char level representation.
You may need a little coding to process the former representation. But no coding is needed for the latter.

**Comment by gaziway** [comment]
in doing so I would like to explore the subword relations like in: https://github.com/claravania/subword-lstm-lm
thank you anyway!
